import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const PerfilStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#8B5CF6',
  },
  gradientBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  floatingElement: {
    position: 'absolute',
    borderRadius: 100,
    opacity: 0.1,
  },
  element1: {
    width: 200,
    height: 200,
    backgroundColor: '#FFFFFF',
    top: -100,
    right: -100,
  },
  element2: {
    width: 150,
    height: 150,
    backgroundColor: '#FFFFFF',
    bottom: 100,
    left: -75,
  },
  element3: {
    width: 100,
    height: 100,
    backgroundColor: '#FFFFFF',
    top: height * 0.3,
    right: -50,
  },
  content: {
    flex: 1,
    paddingHorizontal: width * 0.06,
    paddingTop: height * 0.05,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  headerLabel: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 14,
    fontWeight: '500',
  },
  mainTitle: {
    color: 'white',
    fontSize: 36,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: height * 0.04,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  profileSection: {
    alignItems: 'center',
    marginBottom: height * 0.04,
  },
  profileImageContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  imageGlow: {
    position: 'absolute',
    width: width * 0.35,
    height: width * 0.35,
    borderRadius: width * 0.175,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    top: -5,
    left: -5,
    zIndex: -1,
  },
  profileImage: {
    width: width * 0.3,
    height: width * 0.3,
    borderRadius: width * 0.15,
    borderWidth: 4,
    borderColor: 'white',
  },
  profileBadge: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFD700',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 16,
  },
  configButton: {
    borderRadius: 25,
    overflow: 'hidden',
  },
  buttonGradient: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 15,
    paddingHorizontal: 35,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  configButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  infoCardsContainer: {
    flex: 1,
  },
  infoCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 20,
    padding: 20,
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    position: 'relative',
    overflow: 'hidden',
  },
  cardIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  cardIconText: {
    fontSize: 20,
  },
  cardContent: {
    flex: 1,
  },
  cardLabel: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 14,
    fontWeight: '500',
  },
  cardValue: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 2,
  },
  cardAccent: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 4,
    backgroundColor: '#FFD700',
  },
  backButtonPremium: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  backButtonText: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 25,
    padding: 4,
    marginBottom: 25,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  tabText: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 13,
    fontWeight: '600',
  },
  activeTabText: {
    color: '#8B5CF6',
    fontSize: 13,
    fontWeight: '700',
  },
  termsContainer: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 20,
  },
  termsHeader: {
    backgroundColor: '#8B5CF6',
    padding: 15,
    alignItems: 'center',
  },
  termsHeaderText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  termsScroll: {
    flex: 1,
  },
  termsContent: {
    padding: 20,
  },
  termSection: {
    marginBottom: 20,
  },
  termsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 10,
  },
  termsText: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 6,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  checkboxActive: {
    backgroundColor: 'white',
    borderColor: 'white',
  },
  checkmark: {
    color: '#8B5CF6',
    fontSize: 16,
    fontWeight: 'bold',
  },
  checkboxText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '500',
  },
  acceptButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 15,
    borderRadius: 25,
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  acceptButtonActive: {
    backgroundColor: 'white',
    borderColor: 'white',
  },
  acceptButtonText: {
    color: '#8B5CF6',
    fontSize: 16,
    fontWeight: '700',
  },
  infoSectionPremium: {
    flex: 1,
    justifyContent: 'center',
  },
  premiumInfoCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    padding: 25,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  cardIconLarge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
  },
  cardIconLargeText: {
    fontSize: 24,
  },
  cardContentLarge: {
    flex: 1,
  },
  premiumCardTitle: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  premiumCardSubtitle: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '500',
  },
  cardArrowContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardArrow: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  featuredButton: {
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    borderRadius: 25,
    overflow: 'hidden',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  featuredButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    paddingHorizontal: 25,
  },
  featuredButtonIcon: {
    fontSize: 20,
    marginRight: 10,
  },
  featuredButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  bottomNavContainer: {
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  bottomNav: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 25,
    paddingVertical: 15,
    paddingHorizontal: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 15,
    position: 'relative',
  },
  navItemActive: {
    backgroundColor: '#8B5CF6',
    transform: [{ scale: 1.1 }],
  },
  navIcon: {
    fontSize: 20,
    color: '#6B7280',
  },
  navIconActive: {
    color: 'white',
  },
  navIndicator: {
    position: 'absolute',
    bottom: -8,
    width: 20,
    height: 3,
    backgroundColor: '#8B5CF6',
    borderRadius: 2,
  },
});

export { PerfilStyles };
